version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    expose:
      - 2001
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
    image: tungseo2011/api-orderus:v1.0

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - app

  postgres:
    image: tungseo2011/postgres:15-alpine
    restart: always
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=apiOrder
      - POSTGRES_USER=tungseo

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email tungseo201@gmail.com -d api-orderus.name.vn --agree-tos

volumes:
  postgresqldata:

networks:
  backend:
    driver: bridge
